name: GitHub-Profile-Summary-Cards

on:
  schedule: 
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:  
          GITHUB_TOKEN: ${{ secrets.THAM9500 }}
        with:
          USERNAME: ${{ github.repository_owner }}
          COMMIT_MESSAGE: git update profile

# Credit: https://github.com/marketplace/actions/github-profile-summary-cards