name: GitHub Profile Summary Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 1 * *"

jobs:
  build:
    name: generate-github-profile-summary-cards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_ACCESS_TOKEN }}
        with:
          USERNAME: tham9500
          COMMIT_MESSAGE: Update profile stat weekly
          SHOW_TITLE: true
          SHOW_TIME: false

# Credit: https://github.com/marketplace/actions/github-profile-summary-cards